import '../styles/_global.scss';
import '@mantine/core/styles.css';

import { AppMantineProvider, AppSessionProvider } from '../model';
import { ColorSchemeScript } from '@mantine/core';
import styles from './_layout-styles.module.scss';

export const metadata = {
  title: 'Chat App',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={styles['body']}>
        <AppSessionProvider>
          <AppMantineProvider>
            <main className={styles['main']}>{children}</main>
          </AppMantineProvider>
        </AppSessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
