import '../../styles/global.css';

export const metadata = {
  title: 'Welcome to chat-app-frontend',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <main className="flex-1 bg-slate-200">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
